# Generated by Django 2.1.4 on 2020-06-04 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_user_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupPrivilege',
            fields=[
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.Group')),
                ('privilege_level', models.CharField(choices=[(None, 'Ei roolia'), ('browse', 'Selaaja'), ('edit', 'Asiantuntija'), ('create', 'Vastuuhenkilö'), ('admin', 'Pääkäyttäjä')], default=None, max_length=6, null=True)),
            ],
        ),
    ]
