# Generated by Django 2.1.4 on 2020-06-04 11:15

from django.contrib.auth.models import Group
from django.db import migrations

GROUPS = ["admin", "secretary", "planner"]

# Delete groups that used to be generated in 0002 if
# they exist and are unused
def delete_groups(apps, schema_editor):
    for group in GROUPS:
        try:
            group_obj = Group.objects.get(name=group)
            if not group_obj.user_set.count() and group_obj.name in GROUPS:
                group_obj.delete()

        except Group.DoesNotExist:
            pass

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_groupprivilege'),
    ]

    operations = [migrations.RunPython(delete_groups)]
