# Generated by Django 2.2.13 on 2020-09-02 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('users', '0004_auto_20200604_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='additional_groups',
            field=models.ManyToManyField(blank=True, related_name='additional_users', to='auth.Group', verbose_name='additional groups'),
        ),
    ]
