# Generated by Django 2.2.13 on 2021-08-10 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_additional_groups'),
    ]

    def fix_admin_permissions(apps, schema_editor):
        GroupPrivilege = apps.get_model('users', 'GroupPrivilege')

        for gp in GroupPrivilege.objects.filter(privilege_level='admin'):
            users = gp.group.user_set.all()
            additional_users = gp.group.additional_users.all()

            for user in users.union(additional_users):
                user.is_superuser = True
                user.save()

    operations = [
        migrations.RunPython(fix_admin_permissions, migrations.RunPython.noop),
    ]
