# Generated by Django 2.2.13 on 2021-09-01 08:14
import requests

from django.db import migrations, models
from django.conf import settings

from users.helpers import get_graph_api_access_token


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_fix_admin_rights'),
    ]

    def set_ad_ids(apps, schema_editor):
        User = apps.get_model('users', 'User')
        for user in User.objects.all():
            if not user.ad_id:
                token = get_graph_api_access_token()
                if not token or not user.email:
                    return

                response = requests.get(
                    f"{settings.GRAPH_API_BASE_URL}/v1.0/users/?$search=\"mail:{user.email}\"",
                    headers={
                        "Authorization": f"Bearer {token}",
                        "consistencyLevel": "eventual",
                    },
                )

                if response:
                    try:
                        user.ad_id = response.json().get("value")[0]["id"]
                        user.save()
                    except (TypeError, IndexError, KeyError):
                        pass


    operations = [
        migrations.AddField(
            model_name='user',
            name='ad_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='AD user id'),
        ),
        migrations.RunPython(set_ad_ids, migrations.RunPython.noop)
    ]
