# Generated by Django 3.2.10 on 2022-05-05 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hide_from_ui',
            field=models.BooleanField(default=False, verbose_name='hide from ui'),
        ),
    ]
