kind: Service
apiVersion: v1
metadata:
  name: api
spec:
  selector:
    app: api
  type: ClusterIP
  ports:
    - protocol: TCP
      name: api
      port: 8000
      targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: api
    spec:
      securityContext:
        runAsUser: 1002
        fsGroup: 1003
      imagePullSecrets:
      - name: dockerhub-kaavapino
      volumes:
        - name: media
          persistentVolumeClaim:
            claimName: media-data
      containers:
      - name: api
        image: kleklekle/spia:kaavapino-api-${CICD_EXECUTION_SEQUENCE}-${CICD_GIT_COMMIT}
        volumeMounts:
        - mountPath: "/srv/media"
          name: media
        ports:
        - containerPort: 8000
        env:
          - name: ALLOWED_HOSTS
            valueFrom:
              secretKeyRef:
                name: api
                key: ALLOWED_HOSTS
          - name: WWW_ROOT
            valueFrom:
              secretKeyRef:
                name: api
                key: WWW_ROOT
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: api
                key: DATABASE_URL
          - name: TOKEN_AUTH_ACCEPTED_AUDIENCE
            valueFrom:
              secretKeyRef:
                name: api
                key: TOKEN_AUTH_ACCEPTED_AUDIENCE
          - name: TOKEN_AUTH_ACCEPTED_SCOPE_PREFIX
            valueFrom:
              secretKeyRef:
                name: api
                key: TOKEN_AUTH_ACCEPTED_SCOPE_PREFIX
          - name: REQUIRE_API_SCOPE_FOR_AUTHENTICATION
            valueFrom:
              secretKeyRef:
                name: api
                key: REQUIRE_API_SCOPE_FOR_AUTHENTICATION
          - name: TOKEN_AUTH_AUTHSERVER_URL
            valueFrom:
              secretKeyRef:
                name: api
                key: TOKEN_AUTH_AUTHSERVER_URL
          - name: USE_X_FORWARDED_HOST
            valueFrom:
              secretKeyRef:
                name: api
                key: USE_X_FORWARDED_HOST
          - name: CSRF_COOKIE_DOMAIN
            valueFrom:
              secretKeyRef:
                name: api
                key: CSRF_COOKIE_DOMAIN
          - name: CSRF_TRUSTED_ORIGINS
            valueFrom:
              secretKeyRef:
                name: api
                key: CSRF_TRUSTED_ORIGINS
          - name: SOCIAL_AUTH_TUNNISTAMO_KEY
            valueFrom:
              secretKeyRef:
                name: api
                key: SOCIAL_AUTH_TUNNISTAMO_KEY
          - name: SOCIAL_AUTH_TUNNISTAMO_SECRET
            valueFrom:
              secretKeyRef:
                name: api
                key: SOCIAL_AUTH_TUNNISTAMO_SECRET
          - name: SOCIAL_AUTH_TUNNISTAMO_OIDC_ENDPOINT
            valueFrom:
              secretKeyRef:
                name: api
                key: SOCIAL_AUTH_TUNNISTAMO_OIDC_ENDPOINT
          - name: KAAVOITUS_API_AUTH_TOKEN
            valueFrom:
              secretKeyRef:
                name: api
                key: KAAVOITUS_API_AUTH_TOKEN
          - name: KAAVOITUS_API_BASE_URL
            valueFrom:
              secretKeyRef:
                name: api
                key: KAAVOITUS_API_BASE_URL
          - name: DOCUMENT_EDIT_URL_FORMAT
            valueFrom:
              secretKeyRef:
                name: api
                key: DOCUMENT_EDIT_URL_FORMAT
          - name: GRAPH_API_LOGIN_BASE_URL
            valueFrom:
              secretKeyRef:
                name: api
                key: GRAPH_API_LOGIN_BASE_URL
          - name: GRAPH_API_BASE_URL
            valueFrom:
              secretKeyRef:
                name: api
                key: GRAPH_API_BASE_URL
          - name: GRAPH_API_APPLICATION_ID
            valueFrom:
              secretKeyRef:
                name: api
                key: GRAPH_API_APPLICATION_ID
          - name: GRAPH_API_TENANT_ID
            valueFrom:
              secretKeyRef:
                name: api
                key: GRAPH_API_TENANT_ID
          - name: GRAPH_API_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: api
                key: GRAPH_API_CLIENT_SECRET
---
kind: Service
apiVersion: v1
metadata:
  name: api-django-q
spec:
  selector:
    app: api-django-q
  type: ClusterIP
  ports:
    - protocol: TCP
      name: api-django-q
      port: 8000
      targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-django-q
  labels:
    app: api-django-q
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-django-q
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: api-django-q
    spec:
      securityContext:
        runAsUser: 1002
        fsGroup: 1003
      imagePullSecrets:
      - name: dockerhub-kaavapino
      volumes:
        - name: media
          persistentVolumeClaim:
            claimName: media-data
      containers:
      - name: api
        image: kleklekle/spia:kaavapino-api-${CICD_EXECUTION_SEQUENCE}-${CICD_GIT_COMMIT}
        volumeMounts:
        - mountPath: "/srv/media"
          name: media
          readOnly: true
        env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: api
                key: DATABASE_URL
          - name: KAAVOITUS_API_AUTH_TOKEN
            valueFrom:
              secretKeyRef:
                name: api
                key: KAAVOITUS_API_AUTH_TOKEN
          - name: KAAVOITUS_API_BASE_URL
            valueFrom:
              secretKeyRef:
                name: api
                key: KAAVOITUS_API_BASE_URL
          - name: DOCUMENT_EDIT_URL_FORMAT
            valueFrom:
              secretKeyRef:
                name: api
                key: DOCUMENT_EDIT_URL_FORMAT
          - name: GRAPH_API_LOGIN_BASE_URL
            valueFrom:
              secretKeyRef:
                name: api
                key: GRAPH_API_LOGIN_BASE_URL
          - name: GRAPH_API_BASE_URL
            valueFrom:
              secretKeyRef:
                name: api
                key: GRAPH_API_BASE_URL
          - name: GRAPH_API_APPLICATION_ID
            valueFrom:
              secretKeyRef:
                name: api
                key: GRAPH_API_APPLICATION_ID
          - name: GRAPH_API_TENANT_ID
            valueFrom:
              secretKeyRef:
                name: api
                key: GRAPH_API_TENANT_ID
          - name: GRAPH_API_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: api
                key: GRAPH_API_CLIENT_SECRET
          - name: IS_DJANGO_Q
            value: "yes"
          - name: ALLOWED_HOSTS
            value: ""
          - name: CSRF_TRUSTED_ORIGINS
            value: ""

