kind: Service
apiVersion: v1
metadata:
  name: api
spec:
  selector:
    app: api
  type: ClusterIP
  ports:
    - protocol: TCP
      name: api
      port: 8000
      targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      imagePullSecrets:
      - name: pipeline-docker-registry
      containers:
      - name: api
        image: ${CICD_REGISTRY}/api:${CICD_EXECUTION_SEQUENCE}-${CICD_GIT_COMMIT}
        command: ["/code/deploy/server.sh"]
        args: ["start_production"]
        ports:
        - containerPort: 8000
        env:
          - name: ALLOWED_HOSTS
            valueFrom:
              secretKeyRef:
                name: api
                key: ALLOWED_HOSTS
          - name: WWW_ROOT
            valueFrom:
              secretKeyRef:
                name: api
                key: WWW_ROOT
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: api
                key: DATABASE_URL
          - name: TOKEN_AUTH_ACCEPTED_AUDIENCE
            valueFrom:
              secretKeyRef:
                name: api
                key: TOKEN_AUTH_ACCEPTED_AUDIENCE
          - name: TOKEN_AUTH_ACCEPTED_SCOPE_PREFIX
            valueFrom:
              secretKeyRef:
                name: api
                key: TOKEN_AUTH_ACCEPTED_SCOPE_PREFIX
          - name: REQUIRE_API_SCOPE_FOR_AUTHENTICATION
            valueFrom:
              secretKeyRef:
                name: api
                key: REQUIRE_API_SCOPE_FOR_AUTHENTICATION
          - name: TOKEN_AUTH_AUTHSERVER_URL
            valueFrom:
              secretKeyRef:
                name: api
                key: TOKEN_AUTH_AUTHSERVER_URL
          - name: USE_X_FORWARDED_HOST
            valueFrom:
              secretKeyRef:
                name: api
                key: USE_X_FORWARDED_HOST
          - name: CSRF_COOKIE_DOMAIN
            valueFrom:
              secretKeyRef:
                name: api
                key: CSRF_COOKIE_DOMAIN
          - name: CSRF_TRUSTED_ORIGINS
            valueFrom:
              secretKeyRef:
                name: api
                key: CSRF_TRUSTED_ORIGINS
