# Generated by Django 2.0 on 2018-01-02 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('project_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.ProjectType', verbose_name='project type')),
                ('file', models.FileField(upload_to='', verbose_name='file')),
            ],
            options={
                'verbose_name': 'document template',
                'verbose_name_plural': 'document templates',
            },
        ),
    ]
