# Generated by Django 2.0 on 2018-01-03 21:39

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_add_document_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='slug',
        ),
        migrations.AddField(
            model_name='attribute',
            name='identifier',
            field=models.CharField(db_index=True, max_length=50, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[\\w]+\\Z'), "Enter a valid 'identifier' consisting of Unicode letters, numbers or underscores.", 'invalid')], verbose_name='identifier'),
        ),
        migrations.AddField(
            model_name='attributevaluechoice',
            name='identifier',
            field=models.CharField(db_index=True, max_length=50, validators=[django.core.validators.RegexValidator(re.compile('^[\\w]+\\Z'), "Enter a valid 'identifier' consisting of Unicode letters, numbers or underscores.", 'invalid')], verbose_name='identifier'),
        ),
        migrations.RemoveField(
            model_name='attributevaluechoice',
            name='slug',
        ),
        migrations.AlterUniqueTogether(
            name='attributevaluechoice',
            unique_together={('attribute', 'identifier')},
        ),
    ]
