# Generated by Django 2.0 on 2018-01-06 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_add_geometry_field_to_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='identifier',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='identifier'),
        ),
    ]
