# Generated by Django 2.0 on 2018-01-06 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_add_identifier_to_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='multiple_choice',
            field=models.BooleanField(default=False, verbose_name='multiple choice'),
        ),
        migrations.AddField(
            model_name='attributevaluechoice',
            name='index',
            field=models.PositiveIntegerField(default=0, verbose_name='index'),
        ),
        migrations.AlterUniqueTogether(
            name='attributevaluechoice',
            unique_together={('attribute', 'index'), ('attribute', 'identifier')},
        ),
    ]
