# Generated by Django 2.0 on 2018-01-07 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_increase_choice_identifier_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attributevaluechoice',
            options={'ordering': ('index',), 'verbose_name': 'attribute value choice', 'verbose_name_plural': 'attribute value choices'},
        ),
        migrations.AddField(
            model_name='project',
            name='phase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='projects.ProjectPhase', verbose_name='phase'),
        ),
        migrations.AlterField(
            model_name='projectphase',
            name='project_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='projects.ProjectType', verbose_name='project type'),
        ),
    ]
