# Generated by Django 2.0 on 2018-01-05 12:41

from django.db import migrations, models


def delete_attributes(apps, schema_editor):
    attribute_model = apps.get_model('projects', 'Attribute')
    attribute_model.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_add_phase_to_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='value_type',
            field=models.CharField(choices=[('integer', 'integer'), ('short_string', 'short string'), ('long_string', 'long string'), ('boolean', 'boolean'), ('date', 'date')], max_length=64, verbose_name='value type'),
        ),
        migrations.RunPython(delete_attributes, migrations.RunPython.noop),
    ]
