# Generated by Django 2.0 on 2018-01-12 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_two_attribute_string_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPhaseSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('index', models.PositiveIntegerField(blank=True, null=True, verbose_name='index')),
            ],
            options={
                'verbose_name': 'project phase section',
                'verbose_name_plural': 'project phase sections',
                'ordering': ('phase', 'index'),
            },
        ),
        migrations.CreateModel(
            name='ProjectPhaseSectionAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated', models.BooleanField(verbose_name='generated')),
                ('required', models.BooleanField(verbose_name='required')),
                ('index', models.PositiveIntegerField(blank=True, null=True, verbose_name='index')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Attribute', verbose_name='attribute')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.ProjectPhaseSection', verbose_name='phase section')),
            ],
            options={
                'verbose_name': 'project phase section attribute',
                'verbose_name_plural': 'project phase section attributes',
            },
        ),
        migrations.RemoveField(
            model_name='projectphaseattribute',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='projectphaseattribute',
            name='phase',
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('id',), 'verbose_name': 'project', 'verbose_name_plural': 'projects'},
        ),
        migrations.AlterModelOptions(
            name='projectphase',
            options={'ordering': ('project_type', 'index'), 'verbose_name': 'project phase', 'verbose_name_plural': 'project phases'},
        ),
        migrations.AlterModelOptions(
            name='projecttype',
            options={'ordering': ('name',), 'verbose_name': 'project type', 'verbose_name_plural': 'project types'},
        ),
        migrations.RemoveField(
            model_name='projectphase',
            name='attributes',
        ),
        migrations.DeleteModel(
            name='ProjectPhaseAttribute',
        ),
        migrations.AddField(
            model_name='projectphasesection',
            name='attributes',
            field=models.ManyToManyField(related_name='phase_sections', through='projects.ProjectPhaseSectionAttribute', to='projects.Attribute', verbose_name='attributes'),
        ),
        migrations.AddField(
            model_name='projectphasesection',
            name='phase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='projects.ProjectPhase', verbose_name='phase'),
        ),
        migrations.AlterUniqueTogether(
            name='projectphasesection',
            unique_together={('phase', 'index')},
        ),
    ]
