# Generated by Django 2.0 on 2018-01-15 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_add_project_phase_section'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectphasesectionattribute',
            options={'ordering': ('section', 'index'), 'verbose_name': 'project phase section attribute', 'verbose_name_plural': 'project phase section attributes'},
        ),
        migrations.AlterField(
            model_name='projectphase',
            name='index',
            field=models.PositiveIntegerField(default=0, verbose_name='index'),
        ),
        migrations.AlterField(
            model_name='projectphasesection',
            name='index',
            field=models.PositiveIntegerField(default=0, verbose_name='index'),
        ),
        migrations.AlterField(
            model_name='projectphasesectionattribute',
            name='index',
            field=models.PositiveIntegerField(default=0, verbose_name='index'),
        ),
        migrations.AlterUniqueTogether(
            name='projectphasesectionattribute',
            unique_together={('section', 'index')},
        ),
    ]
