# Generated by Django 2.0.1 on 2018-01-28 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_change_documents_relate_to_phases'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectphase',
            name='color_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='color code'),
        ),
    ]
