# Generated by Django 2.0.1 on 2018-02-02 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_add_help_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='help_text',
            field=models.TextField(blank=True, default='', verbose_name='Help text'),
            preserve_default=False,
        ),
    ]
