# Generated by Django 2.0.1 on 2018-02-07 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_add_project_attribute_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectphase',
            options={'ordering': ('index',), 'verbose_name': 'project phase', 'verbose_name_plural': 'project phases'},
        ),
        migrations.AlterModelOptions(
            name='projectphasesection',
            options={'ordering': ('index',), 'verbose_name': 'project phase section', 'verbose_name_plural': 'project phase sections'},
        ),
        migrations.AlterModelOptions(
            name='projectphasesectionattribute',
            options={'ordering': ('index',), 'verbose_name': 'project phase section attribute', 'verbose_name_plural': 'project phase section attributes'},
        ),
        migrations.AlterModelOptions(
            name='attribute',
            options={'ordering': ('identifier',), 'verbose_name': 'attribute', 'verbose_name_plural': 'attributes'},
        ),
        migrations.AlterField(
            model_name='attribute',
            name='value_type',
            field=models.CharField(choices=[('integer', 'integer'), ('short_string', 'short string'), ('long_string', 'long string'), ('boolean', 'boolean'), ('date', 'date'), ('user', 'user'), ('geometry', 'geometry'), ('image', 'image')], max_length=64, verbose_name='value type'),
        ),
        migrations.AlterField(
            model_name='projectphase',
            name='index',
            field=models.PositiveIntegerField(verbose_name='index'),
        ),
        migrations.AlterField(
            model_name='projectphasesection',
            name='index',
            field=models.PositiveIntegerField(verbose_name='index'),
        ),
        migrations.AlterField(
            model_name='projectphasesectionattribute',
            name='index',
            field=models.PositiveIntegerField(verbose_name='index'),
        ),
        migrations.AlterUniqueTogether(
            name='projectphase',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='projectphasesection',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='projectphasesectionattribute',
            unique_together=set(),
        ),
    ]
