# Generated by Django 2.0.1 on 2018-02-06 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0018_nonunique_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPhaseLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phase_logs', to='projects.ProjectPhase', verbose_name='phase')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phase_logs', to='projects.Project', verbose_name='project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='phase_logs', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'project phase log entry',
                'verbose_name_plural': 'project phase log entries',
                'ordering': ('created_at',),
            },
        ),
        migrations.AlterField(
            model_name='attribute',
            name='value_type',
            field=models.CharField(choices=[('integer', 'integer'), ('short_string', 'short string'), ('long_string', 'long string'), ('boolean', 'boolean'), ('date', 'date'), ('user', 'user'), ('geometry', 'geometry'), ('image', 'image')], max_length=64, verbose_name='value type'),
        ),
    ]
