# Generated by Django 2.1.2 on 2018-10-29 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_add_relies_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectphasesectionattribute',
            name='relies_on',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.ProjectPhaseSectionAttribute', verbose_name='relies on'),
        ),
    ]
