# Generated by Django 2.1.2 on 2018-10-29 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_alter_relies_on_related_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='public',
            field=models.BooleanField(default=False, verbose_name='public information'),
        ),
    ]
