# Generated by Django 2.1.2 on 2018-11-05 10:39

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_add_matrix_attribute'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttype',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='metadata'),
        ),
    ]
