# Generated by Django 2.1.2 on 2018-11-05 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0025_projecttype_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='fieldset_attributes',
            field=models.ManyToManyField(related_name='fieldsets', to='projects.Attribute'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='value_type',
            field=models.CharField(choices=[('fieldset', 'fieldset'), ('integer', 'integer'), ('short_string', 'short string'), ('long_string', 'long string'), ('boolean', 'boolean'), ('date', 'date'), ('user', 'user'), ('geometry', 'geometry'), ('image', 'image')], max_length=64, verbose_name='value type'),
        ),
    ]
