# Generated by Django 2.1.2 on 2018-11-07 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0025_projecttype_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectAttributeFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', verbose_name='file')),
            ],
            options={
                'verbose_name': 'project attribute file',
                'verbose_name_plural': 'project attribute files',
            },
        ),
        migrations.RemoveField(
            model_name='projectattributeimage',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='projectattributeimage',
            name='project',
        ),
        migrations.AlterField(
            model_name='attribute',
            name='value_type',
            field=models.CharField(choices=[('integer', 'integer'), ('short_string', 'short string'), ('long_string', 'long string'), ('boolean', 'boolean'), ('date', 'date'), ('user', 'user'), ('geometry', 'geometry'), ('image', 'image'), ('file', 'file')], max_length=64, verbose_name='value type'),
        ),
        migrations.DeleteModel(
            name='ProjectAttributeImage',
        ),
        migrations.AddField(
            model_name='projectattributefile',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='projects.Attribute', verbose_name='attribute'),
        ),
        migrations.AddField(
            model_name='projectattributefile',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='projects.Project', verbose_name='project'),
        ),
    ]
