# Generated by Django 2.1.2 on 2018-11-06 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0027_private_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectphasesectionattribute',
            name='generated',
        ),
        migrations.RemoveField(
            model_name='projectphasesectionattribute',
            name='required',
        ),
        migrations.AddField(
            model_name='attribute',
            name='generated',
            field=models.BooleanField(default=False, verbose_name='generated'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='required',
            field=models.BooleanField(default=False, verbose_name='required'),
        ),
    ]
