# Generated by Django 2.1.2 on 2018-11-08 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0028_move_required_and_generated_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldSetAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField(default=0, verbose_name='index')),
            ],
            options={
                'verbose_name': 'fieldset attribute',
                'verbose_name_plural': 'fieldset attributes',
                'ordering': ('index',),
            },
        ),
        migrations.AlterField(
            model_name='attribute',
            name='value_type',
            field=models.CharField(choices=[('fieldset', 'fieldset'), ('integer', 'integer'), ('short_string', 'short string'), ('long_string', 'long string'), ('boolean', 'boolean'), ('date', 'date'), ('user', 'user'), ('geometry', 'geometry'), ('image', 'image'), ('file', 'file')], max_length=64, verbose_name='value type'),
        ),
        migrations.AddField(
            model_name='fieldsetattribute',
            name='attribute_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fieldset_attribute_source', to='projects.Attribute'),
        ),
        migrations.AddField(
            model_name='fieldsetattribute',
            name='attribute_target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fieldset_attribute_target', to='projects.Attribute'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='fieldset_attributes',
            field=models.ManyToManyField(related_name='fieldsets', through='projects.FieldSetAttribute', to='projects.Attribute'),
        ),
    ]
