# Generated by Django 2.1.2 on 2018-11-21 14:50

from django.db import migrations
import private_storage.fields
import projects.models.project


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0029_add_fieldset_attribute_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectattributefile',
            name='file',
            field=private_storage.fields.PrivateFileField(max_length=255, storage=projects.models.project.KaavapinoPrivateStorage(base_url='/media/projects/', url_postfix='projects'), upload_to='', verbose_name='File'),
        ),
    ]
