# Generated by Django 2.1.2 on 2018-11-30 12:44

from django.db import migrations
import private_storage.fields
import projects.models.utils


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0032_projectcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttemplate',
            name='file',
            field=private_storage.fields.PrivateFileField(max_length=255, storage=projects.models.utils.KaavapinoPrivateStorage(), upload_to='', verbose_name='File'),
        ),
    ]
