# Generated by Django 2.1.2 on 2018-12-03 12:31

from django.db import migrations, models
import private_storage.fields
import projects.models.utils


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0033_private_document_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttemplate',
            name='slug',
            field=models.SlugField(),
            preserve_default=False,
        ),
    ]
