# Generated by Django 2.1.2 on 2018-12-04 11:28

from django.db import migrations, models
import private_storage.fields
import projects.models.utils


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0034_add_document_slug_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='public',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='documenttemplate',
            name='file',
            field=private_storage.fields.PrivateFileField(max_length=255, storage=projects.models.utils.KaavapinoPrivateStorage(base_url='/media/document_templates/', url_postfix='document_templates'), upload_to='', verbose_name='File'),
        ),
    ]
