# Generated by Django 2.1.2 on 2018-12-12 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0035_private_flag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('project_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='projects.ProjectType', verbose_name='project type')),
            ],
            options={
                'verbose_name': 'report',
                'verbose_name_plural': 'reports',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='ReportAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_attributes', to='projects.Attribute', verbose_name='attribute')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_attributes', to='projects.Report', verbose_name='report')),
            ],
            options={
                'verbose_name': 'report attribute',
                'verbose_name_plural': 'report attributes',
                'ordering': ('id',),
            },
        ),
        migrations.AlterUniqueTogether(
            name='reportattribute',
            unique_together={('report', 'attribute')},
        ),
    ]
