# Generated by Django 2.1.2 on 2018-12-13 15:26

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0036_add_link_attribute'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectAttributeMultipolygonGeometry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='geometry',
        ),
        migrations.AlterField(
            model_name='attribute',
            name='value_type',
            field=models.CharField(
                choices=[('fieldset', 'fieldset'), ('integer', 'integer'), ('short_string', 'short string'),
                         ('long_string', 'long string'), ('boolean', 'boolean'), ('date', 'date'), ('user', 'user'),
                         ('geometry', 'geometry'), ('image', 'image'), ('file', 'file'), ('link', 'link')],
                max_length=64, verbose_name='value type'),
        ),
        migrations.AddField(
            model_name='projectattributemultipolygongeometry',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geometries',
                                    to='projects.Attribute', verbose_name='attribute'),
        ),
        migrations.AddField(
            model_name='projectattributemultipolygongeometry',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geometries',
                                    to='projects.Project', verbose_name='project'),
        ),
    ]
