# Generated by Django 2.1.4 on 2018-12-21 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0043_attribute_calculations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='value_type',
            field=models.CharField(choices=[('fieldset', 'fieldset'), ('integer', 'integer'), ('decimal', 'decimal'), ('short_string', 'short string'), ('long_string', 'long string'), ('boolean', 'boolean'), ('date', 'date'), ('user', 'user'), ('geometry', 'geometry'), ('image', 'image'), ('file', 'file'), ('link', 'link')], max_length=64, verbose_name='value type'),
        ),
    ]
