# Generated by Django 2.1.4 on 2019-01-22 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0047_attribute_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectattributefile',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
    ]
