# Generated by Django 2.1.4 on 2019-01-22 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0049_projectcomment_generated'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='broadcast_changes',
            field=models.BooleanField(default=False),
        ),
    ]
