# Generated by Django 2.1.4 on 2019-01-24 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0050_attribute_broadcast_changes'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='help_link',
            field=models.URLField(blank=True, null=True, verbose_name='Help link'),
        ),
    ]
