# Generated by Django 2.1.4 on 2020-06-10 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0052_auto_20200603_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='create_draft',
            field=models.BooleanField(default=False, verbose_name='create draft'),
        ),
        migrations.AddField(
            model_name='project',
            name='create_principles',
            field=models.BooleanField(default=False, verbose_name='create principles'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='name'),
        ),
    ]
