# Generated by Django 2.1.4 on 2020-06-11 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0053_auto_20200610_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectphase',
            name='index',
            field=models.PositiveIntegerField(default=0, verbose_name='index'),
        ),
        migrations.AlterField(
            model_name='projectphasesection',
            name='index',
            field=models.PositiveIntegerField(default=0, verbose_name='index'),
        ),
        migrations.AlterField(
            model_name='projectphasesectionattribute',
            name='index',
            field=models.PositiveIntegerField(default=0, verbose_name='index'),
        ),
        migrations.AlterField(
            model_name='projectsubtype',
            name='index',
            field=models.PositiveIntegerField(default=0, verbose_name='index'),
        ),
    ]
