# Generated by Django 2.2.13 on 2020-06-26 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0055_auto_20200617_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectphasesectionattribute',
            name='priority',
        ),
        migrations.AddField(
            model_name='attribute',
            name='display',
            field=models.CharField(choices=[(None, 'default'), ('dropdown', 'dropdown')], default=None, max_length=64, null=True, verbose_name='display style'),
        ),
    ]
