# Generated by Django 2.2.13 on 2020-07-01 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0056_auto_20200626_1425'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectFloorAreaSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('index', models.PositiveIntegerField(default=0, verbose_name='index')),
            ],
            options={
                'verbose_name': 'project floor area section',
                'verbose_name_plural': 'project floor area sections',
                'ordering': ('index',),
            },
        ),
        migrations.CreateModel(
            name='ProjectFloorAreaSectionAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField(default=0, verbose_name='index')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Attribute', verbose_name='attribute')),
                ('relies_on', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.ProjectFloorAreaSectionAttribute', verbose_name='relies on')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.ProjectFloorAreaSection', verbose_name='floor area section')),
            ],
            options={
                'verbose_name': 'project floor area section attribute',
                'verbose_name_plural': 'project floor area section attributes',
                'ordering': ('index',),
            },
        ),
        migrations.AddField(
            model_name='projectfloorareasection',
            name='attributes',
            field=models.ManyToManyField(related_name='floor_area_sections', through='projects.ProjectFloorAreaSectionAttribute', to='projects.Attribute', verbose_name='attributes'),
        ),
        migrations.AddField(
            model_name='projectfloorareasection',
            name='project_subtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floor_area_sections', to='projects.ProjectSubtype', verbose_name='project subtype'),
        ),
    ]
