# Generated by Django 2.2.13 on 2020-07-06 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0057_lastreadtimestamp'),
        ('projects', '0057_auto_20200701_0731'),
    ]

    operations = [
    ]
