# Generated by Django 2.2.13 on 2020-08-28 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0062_auto_20200825_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated', models.BooleanField(default=False, verbose_name='generated')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified at')),
                ('content', models.TextField(verbose_name='content')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments', to='projects.Attribute', verbose_name='field')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='field_comments', to='projects.Project', verbose_name='project')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'field comment',
                'verbose_name_plural': 'field comments',
                'ordering': ('created_at',),
            },
        ),
    ]
