# Generated by Django 2.2.13 on 2020-09-07 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0063_fieldcomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fieldsetattribute',
            options={'verbose_name': 'fieldset attribute', 'verbose_name_plural': 'fieldset attributes'},
        ),
        migrations.RemoveField(
            model_name='fieldsetattribute',
            name='index',
        ),
        migrations.CreateModel(
            name='ProjectPhaseFieldSetAttributeIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField(default=0, verbose_name='index')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.FieldSetAttribute')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.ProjectPhase')),
            ],
        ),
        migrations.AddField(
            model_name='fieldsetattribute',
            name='phase_indices',
            field=models.ManyToManyField(related_name='fieldsets', through='projects.ProjectPhaseFieldSetAttributeIndex', to='projects.ProjectPhase'),
        ),
    ]
