# Generated by Django 2.2.13 on 2020-09-09 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0064_auto_20200907_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectphase',
            name='list_prefix',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='list prefix'),
        ),
    ]
