# Generated by Django 2.2.13 on 2020-08-26 13:05

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0065_projectphase_list_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='autofill_readonly',
            field=models.BooleanField(null=True, verbose_name='read-only autofill field'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='autofill_rule',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='autofill rule'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='related_fields',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='attribute',
            name='searchable',
            field=models.BooleanField(default=False, verbose_name='searchable field'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='updates_autofill',
            field=models.BooleanField(default=False, verbose_name='updates related autofill fields'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='visibility_condition',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), blank=True, null=True, size=None, verbose_name='visibility condition'),
        ),
    ]
