# Generated by Django 2.2.13 on 2020-09-17 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0065_projectphase_list_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='character_limit',
            field=models.PositiveIntegerField(null=True, verbose_name='character limit'),
        ),
    ]
