# Generated by Django 2.2.13 on 2020-09-30 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0066_attribute_autofill_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataRetentionPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, unique=True, verbose_name='label')),
                ('plan_type', models.CharField(choices=[('permanent', 'permanent'), ('processing', 'while processing'), ('custom', 'custom duration after archival')], max_length=10, verbose_name='plan type')),
                ('custom_time', models.PositiveIntegerField(blank=True, null=True, verbose_name='custom time')),
                ('custom_time_unit', models.CharField(blank=True, choices=[('years', 'years'), ('months', 'months'), ('days', 'days')], max_length=6, null=True, verbose_name='unit for custom time')),
            ],
        ),
        migrations.AddField(
            model_name='attribute',
            name='data_retention_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='projects.DataRetentionPlan', verbose_name='data retention plan'),
        ),
    ]
