# Generated by Django 2.2.13 on 2020-09-29 08:17

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('projects', '0066_attribute_autofill_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='visibility_conditions',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True), blank=True, null=True, size=None, verbose_name='visibility condition'),
        ),
        migrations.RemoveField(
            model_name='attribute',
            name='visibility_condition',
        ),
    ]
