# Generated by Django 2.2.13 on 2020-10-05 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0067_data_retention_plan'),
        ('projects', '0067_visibility_conditions'),
    ]

    operations = [
    ]
