# Generated by Django 2.2.13 on 2020-10-07 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0068_merge_20201005_1302'),
        ('projects', '0066_attribute_character_limit'),
    ]

    operations = [
    ]
