# Generated by Django 2.2.13 on 2020-10-07 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0068_attribute_highlight_group'),
        ('projects', '0069_merge_20201007_1704'),
    ]

    operations = [
    ]
