# Generated by Django 2.2.13 on 2020-10-13 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0070_merge_20201007_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='static_property',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
