# Generated by Django 2.2.13 on 2020-10-16 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0071_attribute_static_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='error_message',
            field=models.TextField(blank=True, null=True, verbose_name='error message'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='unique',
            field=models.BooleanField(default=False, verbose_name='unique'),
        ),
    ]
