# Generated by Django 2.2.13 on 2020-10-22 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0072_attribute_project_unique_and_error_message_fields'),
    ]

    def set_pino_numbers(apps, schema_editor):
        Project = apps.get_model('projects', 'Project')

        for project in Project.objects.all():
            project.pino_number = str(project.pk).zfill(7)
            project.save()


    operations = [
        migrations.AddField(
            model_name='project',
            name='pino_number',
            field=models.CharField(max_length=7, null=True, verbose_name='pino number'),
        ),
        migrations.RunPython(set_pino_numbers, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='project',
            name='pino_number',
            field=models.CharField(max_length=7, unique=True, verbose_name='pino number'),
        ),
    ]
