# Generated by Django 2.2.13 on 2020-10-29 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0073_project_pino_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='pino_number',
            field=models.CharField(blank=True, max_length=7, null=True, unique=True, verbose_name='pino number'),
        ),
    ]
