# Generated by Django 2.2.13 on 2020-11-17 13:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0075_deadlines'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deadline',
            name='deadline_type',
        ),
        migrations.AddField(
            model_name='deadline',
            name='deadline_types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('phase_start', 'phase start point'), ('phase_end', 'phase end point'), ('dashed_start', 'dashed line start point'), ('dashed_end', 'dashed line end point'), ('inner_start', 'inner line start point'), ('inner_end', 'inner line end point'), ('milestone', 'milestone')], max_length=64), blank=True, null=True, size=None, verbose_name='deadline types'),
        ),
    ]
