# Generated by Django 2.2.13 on 2020-11-18 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0077_auto_20201117_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdeadline',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='deadline date'),
        ),
    ]
