# Generated by Django 2.2.13 on 2020-11-18 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0078_null_projectdeadline_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectdeadline',
            unique_together={('deadline', 'project')},
        ),
    ]
