# Generated by Django 2.2.13 on 2020-11-18 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0079_projectdeadline_unique_constraint'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectdeadline',
            options={'ordering': ('deadline__index',)},
        ),
    ]
