# Generated by Django 2.2.13 on 2020-11-18 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0080_projectdeadlines_ordering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deadline',
            name='attribute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deadline', to='projects.Attribute', verbose_name='attribute'),
        ),
        migrations.AlterUniqueTogether(
            name='deadline',
            unique_together={('attribute', 'phase'), ('abbreviation', 'subtype')},
        ),
    ]
