# Generated by Django 2.2.13 on 2020-11-23 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0081_deadline_attribute_foreignkey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deadline',
            name='distance_reference_deadlines',
        ),
        migrations.RemoveField(
            model_name='deadline',
            name='min_distance',
        ),
        migrations.CreateModel(
            name='DeadlineDistance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_from_previous', models.IntegerField(default=0, verbose_name='minimum distance from previous deadline')),
                ('deadline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distances_to_previous', to='projects.Deadline', verbose_name='deadline')),
                ('previous_deadline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distances_to_next', to='projects.Deadline', verbose_name='previous deadline')),
            ],
        ),
    ]
