# Generated by Django 2.2.13 on 2020-11-24 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0082_deadlinedistance'),
    ]

    operations = [
        migrations.AddField(
            model_name='deadlinedistance',
            name='date_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='projects.DateType', verbose_name='date type'),
        ),
        migrations.AlterField(
            model_name='datecalculation',
            name='base_date_attribute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Attribute', verbose_name='relies on date from attribute'),
        ),
        migrations.AlterField(
            model_name='datecalculation',
            name='base_date_deadline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Deadline', verbose_name='relies on date from deadline'),
        ),
        migrations.AlterField(
            model_name='deadline',
            name='date_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='projects.DateType', verbose_name='date type'),
        ),
    ]
