# Generated by Django 2.2.13 on 2020-11-25 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0083_auto_20201124_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='edit_privilege',
            field=models.CharField(blank=True, choices=[(None, 'Ei roolia'), ('browse', 'Selaaja'), ('edit', 'Asiantuntija'), ('create', 'Vastuuhenkilö'), ('admin', 'Pääkäyttäjä')], default=None, max_length=6, null=True, verbose_name='privilege for editing'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='owner_editable',
            field=models.BooleanField(default=False, verbose_name='owner can edit'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='owner_viewable',
            field=models.BooleanField(default=True, verbose_name='owner can view'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='view_privilege',
            field=models.CharField(blank=True, choices=[(None, 'Ei roolia'), ('browse', 'Selaaja'), ('edit', 'Asiantuntija'), ('create', 'Vastuuhenkilö'), ('admin', 'Pääkäyttäjä')], default='browse', max_length=6, null=True, verbose_name='privilege for viewing'),
        ),
    ]
