# Generated by Django 2.2.13 on 2020-12-01 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0084_auto_20201125_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datecalculationattribute',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Attribute', verbose_name='relies on date from attribute'),
        ),
    ]
