# Generated by Django 2.2.13 on 2020-12-02 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0085_auto_20201201_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPhaseDeadlineSectionAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField(default=0, verbose_name='index')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Attribute', verbose_name='attribute')),
            ],
            options={
                'verbose_name': 'project phase deadline section item',
                'verbose_name_plural': 'project phase deadline section items',
                'ordering': ('index',),
            },
        ),
        migrations.RemoveField(
            model_name='projectphasedeadlinesection',
            name='deadlines',
        ),
        migrations.DeleteModel(
            name='ProjectPhaseSectionDeadline',
        ),
        migrations.AddField(
            model_name='projectphasedeadlinesectionattribute',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.ProjectPhaseDeadlineSection', verbose_name='deadline phase section'),
        ),
        migrations.AddField(
            model_name='projectphasedeadlinesection',
            name='attributes',
            field=models.ManyToManyField(related_name='phase_deadline_sections', through='projects.ProjectPhaseDeadlineSectionAttribute', to='projects.Attribute', verbose_name='attributes'),
        ),
    ]
