# Generated by Django 2.2.13 on 2020-12-03 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0086_auto_20201202_0818'),
    ]

    operations = [
        migrations.AddField(
            model_name='deadline',
            name='default_to_created_at',
            field=models.BooleanField(default=False, verbose_name='Use created at as value if no attribute or calculations are specified'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='display',
            field=models.CharField(blank=True, choices=[(None, 'default'), ('dropdown', 'dropdown'), ('checkbox', 'checkbox'), ('readonly', 'read only'), ('readonly_checkbox', 'read only checkbox')], default=None, max_length=64, null=True, verbose_name='display style'),
        ),
    ]
