# Generated by Django 2.2.13 on 2020-12-07 06:44

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0087_deadline_default_to_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='identifier',
            field=models.CharField(db_index=True, max_length=60, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[\\w]+\\Z'), "Enter a valid 'identifier' consisting of Unicode letters, numbers or underscores.", 'invalid')], verbose_name='identifier'),
        ),
    ]
