# Generated by Django 2.2.13 on 2020-12-11 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0089_deadlinedatecalculation_not_conditions'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='placeholder_text',
            field=models.TextField(blank=True, null=True, verbose_name='placeholder text'),
        ),
    ]
