# Generated by Django 2.2.13 on 2020-12-10 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0090_attribute_placeholder_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deadlinedistance',
            options={'ordering': ('index',)},
        ),
        migrations.AddField(
            model_name='deadlinedistance',
            name='conditions',
            field=models.ManyToManyField(blank=True, to='projects.Attribute', verbose_name='use rule if any attribute is set'),
        ),
        migrations.AddField(
            model_name='deadlinedistance',
            name='index',
            field=models.PositiveIntegerField(default=0, verbose_name='index'),
        ),
    ]
