# Generated by Django 2.2.13 on 2020-12-17 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0092_projectphasedeadlinesectionattribute_admin_owner_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='owner_edit_override',
            field=models.BooleanField(default=False),
        ),
    ]
