# Generated by Django 2.2.13 on 2021-01-12 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0093_project_owner_edit_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='datecalculation',
            name='date_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='projects.DateType', verbose_name='date type'),
        ),
    ]
