# Generated by Django 2.2.13 on 2021-01-19 05:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0094_datecalculation_date_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectattributefile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created at'),
            preserve_default=False,
        ),
    ]
