# Generated by Django 2.2.13 on 2021-01-20 05:44

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0095_projectattributefile_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='hide_conditions',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True), blank=True, null=True, size=None, verbose_name='hide condition'),
        ),
    ]
