# Generated by Django 2.2.13 on 2021-02-10 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0097_projectdeadline_generated'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectattributefile',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='archived at'),
        ),
    ]
