# Generated by Django 2.2.13 on 2021-02-19 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0099_deadline_confirmation_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='character_limit',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='character limit'),
        ),
    ]
