# Generated by Django 2.2.13 on 2021-02-26 07:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0100_auto_20210219_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldcomment',
            name='fieldset_index',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, null=True, size=None, verbose_name='fieldset index'),
        ),
    ]
