# Generated by Django 2.2.13 on 2021-03-10 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0101_fieldcomment_fieldset_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldcomment',
            name='fieldset_index',
        ),
        migrations.AddField(
            model_name='projectattributefile',
            name='fieldset_path_str',
            field=models.TextField(blank=True, null=True, verbose_name='fieldset path string'),
        ),
        migrations.CreateModel(
            name='ProjectAttributeFileFieldsetPathLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_index', models.PositiveIntegerField(verbose_name='child index')),
                ('index', models.PositiveIntegerField(verbose_name='index')),
                ('parent_fieldset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Attribute', verbose_name='parent fieldset')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fieldset_path_locations', to='projects.ProjectAttributeFile', verbose_name='target file')),
            ],
            options={
                'ordering': ('index',),
                'abstract': False,
                'unique_together': {('index', 'target')},
            },
        ),
        migrations.CreateModel(
            name='FieldCommentFieldsetPathLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_index', models.PositiveIntegerField(verbose_name='child index')),
                ('index', models.PositiveIntegerField(verbose_name='index')),
                ('parent_fieldset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Attribute', verbose_name='parent fieldset')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fieldset_path_locations', to='projects.FieldComment', verbose_name='target comment')),
            ],
            options={
                'ordering': ('index',),
                'abstract': False,
                'unique_together': {('index', 'target')},
            },
        ),
    ]
