# Generated by Django 2.2.13 on 2021-03-31 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0102_fieldset_paths'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCardSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('index', models.PositiveIntegerField(default=0, verbose_name='index')),
            ],
            options={
                'verbose_name': 'project card section',
                'verbose_name_plural': 'project card sections',
                'ordering': ('index',),
            },
        ),
        migrations.CreateModel(
            name='ProjectCardSectionAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_format', models.CharField(blank=True, max_length=255, null=True, verbose_name='date format and text')),
                ('index', models.PositiveIntegerField(default=0, verbose_name='index')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Attribute', verbose_name='attribute')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='projects.ProjectCardSection', verbose_name='project card section')),
            ],
            options={
                'verbose_name': 'project card section attribute',
                'verbose_name_plural': 'project card section attributes',
                'ordering': ('index',),
            },
        ),
    ]
