# Generated by Django 2.2.13 on 2021-04-26 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0105_overviewfilter_overviewfilterattribute'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='overviewfilter',
            options={'verbose_name': 'overview filter', 'verbose_name_plural': 'overview filters'},
        ),
        migrations.AlterModelOptions(
            name='overviewfilterattribute',
            options={'verbose_name': 'overview filter attribute', 'verbose_name_plural': 'overview filter attributes'},
        ),
    ]
