# Generated by Django 2.2.13 on 2021-05-21 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0108_deadline_error_date_type_mismatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='data_source',
            field=models.CharField(blank=True, choices=[('fieldset', 'Same as parent fieldset'), ('/facta/v1/kiinteisto/<pk>/all', 'FACTA'), ('/geoserver/v1/kiinteisto/<pk>/all', 'Geoserver')], max_length=255, null=True, verbose_name='external data source'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='data_source_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='field key for external data source'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='key_attribute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='key_for_attributes', to='projects.Attribute', verbose_name='key attribute for fetching external data'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='key_attribute_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
