# Generated by Django 2.2.13 on 2021-06-08 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0109_external_data_source_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='ad_data_key',
            field=models.CharField(blank=True, choices=[('id', 'id'), ('name', 'name'), ('phone', 'phone'), ('email', 'email'), ('title', 'title'), ('office', 'office')], max_length=6, null=True, verbose_name='AD user data key'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='ad_key_attribute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='projects.Attribute', verbose_name='key attribute for fetching AD user data'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='value_type',
            field=models.CharField(choices=[('fieldset', 'fieldset'), ('integer', 'integer'), ('decimal', 'decimal'), ('short_string', 'short string'), ('long_string', 'long string'), ('rich_text', 'rich text'), ('rich_text_short', 'short rich text'), ('boolean', 'boolean'), ('date', 'date'), ('user', 'user'), ('personnel', 'personnel'), ('geometry', 'geometry'), ('image', 'image'), ('file', 'file'), ('link', 'link'), ('choice', 'choice')], max_length=64, verbose_name='value type'),
        ),
    ]
