# Generated by Django 2.2.13 on 2021-06-10 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0110_ad_integration_model_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='ad_data_key',
            field=models.CharField(blank=True, choices=[('id', 'id'), ('name', 'name'), ('phone', 'phone'), ('email', 'email'), ('title', 'title'), ('office', 'office'), ('company', 'company')], max_length=7, null=True, verbose_name='AD user data key'),
        ),
    ]
