# Generated by Django 2.2.13 on 2021-06-16 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0111_auto_20210610_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttemplate',
            name='image_template',
            field=models.BooleanField(default=False, verbose_name='image template'),
        ),
    ]
