# Generated by Django 2.2.13 on 2021-06-17 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0113_common_project_phase'),
    ]

    def add_common_project_phases(apps, schema_editor):
        DocumentTemplate = apps.get_model('projects', 'DocumentTemplate')

        for template in DocumentTemplate.objects.all():
            template.common_project_phase = template.project_phase.common_project_phase
            template.save()

    operations = [
        migrations.AddField(
            model_name='documenttemplate',
            name='common_project_phase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_templates', to='projects.CommonProjectPhase', verbose_name='project phase'),
        ),
        migrations.RunPython(add_common_project_phases, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='documenttemplate',
            name='project_phase',
        ),
        migrations.AlterField(
            model_name='documenttemplate',
            name='common_project_phase',
            field=models.ForeignKey(null=False, on_delete=django.db.models.deletion.CASCADE, related_name='document_templates', to='projects.CommonProjectPhase', verbose_name='project phase'),
        ),
    ]
