# Generated by Django 2.2.13 on 2021-08-09 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0119_auto_20210809_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportcolumn',
            name='condition',
            field=models.ManyToManyField(blank=True, related_name='report_column_conditions', to='projects.Attribute', verbose_name='condition'),
        ),
    ]
