# Generated by Django 2.2.13 on 2021-08-10 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0120_auto_20210809_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcardsectionattribute',
            name='show_on_mobile',
            field=models.BooleanField(default=True, verbose_name='show on mobile'),
        ),
    ]
