# Generated by Django 2.2.13 on 2021-08-17 07:46

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0121_projectcardsectionattribute_show_on_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcolumn',
            name='custom_display_mapping',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='map automatic display value strings to custom display values'),
        ),
    ]
