# Generated by Django 2.2.13 on 2021-08-17 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0122_reportcolumn_custom_display_mapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcolumn',
            name='preview_only',
            field=models.BooleanField(default=False, verbose_name='only show in preview'),
        ),
    ]
