# Generated by Django 2.2.13 on 2021-08-19 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0123_reportcolumn_preview_only'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('identifier', models.CharField(max_length=255, verbose_name='identifier')),
                ('type', models.CharField(choices=[('exact', 'exact value'), ('multiple', 'multiple choice'), ('range', 'value range'), ('set', 'value is set'), ('not_set', 'value is not set')], max_length=8, verbose_name='filter type')),
                ('attributes_as_choices', models.BooleanField(default=False, verbose_name='use attributes as choices')),
                ('attributes', models.ManyToManyField(to='projects.Attribute', verbose_name='target attributes')),
                ('reports', models.ManyToManyField(related_name='filters', to='projects.Report', verbose_name='usable with reports')),
            ],
        ),
        migrations.CreateModel(
            name='ReportFilterAttributeChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('identifier', models.CharField(max_length=255, verbose_name='identifier')),
                ('value', models.CharField(max_length=255, verbose_name='search value, values or value range')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Attribute', verbose_name='attribute')),
                ('report_filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_choices', to='projects.ReportFilter', verbose_name='filter')),
            ],
        ),
    ]
