# Generated by Django 2.2.13 on 2021-08-27 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0125_documenttemplate__common_project_phases'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDocumentDownloadLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_download_log', to='projects.DocumentTemplate', verbose_name='document template')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_download_log', to='projects.CommonProjectPhase', verbose_name='phase')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_download_log', to='projects.Project', verbose_name='project')),
            ],
        ),
    ]
