# Generated by Django 2.2.13 on 2021-09-01 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0126_documentprojectdownloadlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportfilter',
            options={'verbose_name': 'report filter', 'verbose_name_plural': 'report filters'},
        ),
        migrations.AlterModelOptions(
            name='reportfilterattributechoice',
            options={'verbose_name': 'attribute choice for report filter', 'verbose_name_plural': 'attribute choices for report filters'},
        ),
        migrations.AlterField(
            model_name='attribute',
            name='display',
            field=models.CharField(blank=True, choices=[(None, 'default'), ('dropdown', 'dropdown'), ('checkbox', 'checkbox'), ('readonly', 'read only'), ('readonly_checkbox', 'read only checkbox'), ('simple_integer', 'integer without thousand separator')], default=None, max_length=64, null=True, verbose_name='display style'),
        ),
        migrations.AlterField(
            model_name='documenttemplate',
            name='common_project_phases',
            field=models.ManyToManyField(related_name='document_templates', to='projects.CommonProjectPhase', verbose_name='project phase'),
        ),
    ]
