# Generated by Django 2.2.13 on 2021-09-13 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0127_auto_20210901_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportfilter',
            name='input_type',
            field=models.CharField(choices=[('string', 'string'), ('date', 'date'), ('integer', 'integer')], default='string', max_length=7, verbose_name='filter input type'),
        ),
    ]
