# Generated by Django 2.2.13 on 2021-09-16 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0128_reportfilter_input_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcolumn',
            name='preview_title_column',
            field=models.BooleanField(default=False, verbose_name='use column values as titles in preview'),
        ),
    ]
