# Generated by Django 2.2.13 on 2021-09-17 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0129_reportcolumn_preview_title_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='hidden',
            field=models.BooleanField(default=False, verbose_name='hide report from other views'),
        ),
    ]
