# Generated by Django 2.2.13 on 2021-09-20 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0130_report_hidden'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeAutoValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automatically_sets', to='projects.Attribute', verbose_name='key attribute')),
                ('value_attribute', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='automatic_value', to='projects.Attribute', verbose_name='automatic attribute')),
            ],
        ),
        migrations.CreateModel(
            name='AttributeAutoValueMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_str', models.TextField(verbose_name='key')),
                ('value_str', models.TextField(verbose_name='value')),
                ('auto_attr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='value_map', to='projects.AttributeAutoValue', verbose_name='attribute link')),
            ],
            options={
                'unique_together': {('auto_attr', 'key_str')},
            },
        ),
    ]
