# Generated by Django 2.2.13 on 2021-09-22 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0132_auto_20210921_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcolumn',
            name='postfix_only',
            field=models.BooleanField(default=False, verbose_name='only show postfix as field value'),
        ),
    ]
