# Generated by Django 2.2.13 on 2021-10-08 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0134_auto_20210922_0929'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportcolumnpostfix',
            options={'ordering': ('index',), 'verbose_name': 'report column postfix', 'verbose_name_plural': 'report column postfixes'},
        ),
        migrations.AddField(
            model_name='reportcolumnpostfix',
            name='index',
            field=models.PositiveIntegerField(default=0, verbose_name='index'),
        ),
    ]
