# Generated by Django 2.2.13 on 2021-10-08 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0135_auto_20211008_0839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportcolumnpostfix',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='reportcolumnpostfix',
            name='hide_condition',
        ),
        migrations.AddField(
            model_name='reportcolumnpostfix',
            name='hide_conditions',
            field=models.ManyToManyField(blank=True, related_name='report_column_postfix_hide_conditions', to='projects.Attribute', verbose_name='conditions: hide if...'),
        ),
        migrations.AddField(
            model_name='reportcolumnpostfix',
            name='hide_not_conditions',
            field=models.ManyToManyField(blank=True, related_name='report_column_postfix_hide_not_conditions', to='projects.Attribute', verbose_name='conditions: hide if not...'),
        ),
        migrations.AddField(
            model_name='reportcolumnpostfix',
            name='show_conditions',
            field=models.ManyToManyField(blank=True, related_name='report_column_postfix_show_conditions', to='projects.Attribute', verbose_name='conditions: show if...'),
        ),
        migrations.AddField(
            model_name='reportcolumnpostfix',
            name='show_not_conditions',
            field=models.ManyToManyField(blank=True, related_name='report_column_postfix_show_not_conditions', to='projects.Attribute', verbose_name='conditions: show if not...'),
        ),
    ]
