# Generated by Django 2.2.13 on 2021-10-12 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0136_auto_20211008_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportfilter',
            name='input_type',
            field=models.CharField(choices=[('personnel', 'personnel'), ('string', 'string'), ('date', 'date'), ('integer', 'integer')], default='string', max_length=9, verbose_name='filter input type'),
        ),
    ]
