# Generated by Django 2.2.13 on 2021-10-27 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0137_reportfilter_input_type_personnel'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttemplate',
            name='silent_downloads',
            field=models.BooleanField(default=False, verbose_name="Downloading document doesn't trigger warnings"),
        ),
    ]
