# Generated by Django 3.2.10 on 2021-12-20 14:49

import django.contrib.postgres.fields
import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0139_auto_20211210_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='autofill_rule',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='autofill rule'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='hide_conditions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='hide attribute if any condition applies'), blank=True, null=True, size=None, verbose_name='hide condition'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='visibility_conditions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='show attribute if any condition applies'), blank=True, null=True, size=None, verbose_name='visibility condition'),
        ),
        migrations.AlterField(
            model_name='project',
            name='attribute_data',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='attribute data'),
        ),
        migrations.AlterField(
            model_name='projectphase',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='metadata'),
        ),
        migrations.AlterField(
            model_name='projectsubtype',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='metadata'),
        ),
        migrations.AlterField(
            model_name='projecttype',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='metadata'),
        ),
        migrations.AlterField(
            model_name='reportcolumn',
            name='custom_display_mapping',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='map automatic display value strings to custom display values'),
        ),
    ]
