# Generated by Django 3.2.10 on 2022-04-21 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0141_documenttemplate_project_card_default_template'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attributeautovalue',
            options={'verbose_name': 'attribute auto value map', 'verbose_name_plural': 'attribute auto value maps'},
        ),
        migrations.AlterModelOptions(
            name='attributeautovaluemapping',
            options={'verbose_name': 'attribute auto value mapping', 'verbose_name_plural': 'attribute auto value mappings'},
        ),
        migrations.AlterModelOptions(
            name='datetype',
            options={'verbose_name': 'date type', 'verbose_name_plural': 'date types'},
        ),
        migrations.AlterModelOptions(
            name='deadline',
            options={'ordering': ('index',), 'verbose_name': 'deadline', 'verbose_name_plural': 'deadlines'},
        ),
        migrations.AlterModelOptions(
            name='phaseattributematrixstructure',
            options={'verbose_name': 'phase attribute matrix structure', 'verbose_name_plural': 'phase attribute matrix structure'},
        ),
        migrations.AlterModelOptions(
            name='projectfloorareasectionattributematrixstructure',
            options={'verbose_name': 'project floor area section attribute matrix structure', 'verbose_name_plural': 'project floor area section attribute matrix structures'},
        ),
    ]
