# Generated by Django 3.2.10 on 2022-05-11 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0143_projectcardsection_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcolumn',
            name='generated_new_rows',
            field=models.BooleanField(default=False),
        ),
    ]
