# Generated by Django 3.2.10 on 2022-05-11 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0144_reportcolumn_generated_new_rows'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportcolumn',
            old_name='generated_new_rows',
            new_name='generates_new_rows',
        ),
    ]
