# Generated by Django 3.2.10 on 2022-05-11 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0145_rename_generated_new_rows_reportcolumn_generates_new_rows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportcolumn',
            name='generates_new_rows',
            field=models.BooleanField(default=False, verbose_name='create new column'),
        ),
    ]
