# Generated by Django 3.2.10 on 2022-05-15 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0146_alter_reportcolumn_generates_new_rows'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcardsectionattribute',
            name='custom_label',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='custom label'),
        ),
    ]
