# Generated by Django 3.2.16 on 2023-03-10 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0147_projectcardsectionattribute_custom_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='help_link',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='Help link'),
        ),
    ]
