# Generated by Django 3.2.16 on 2023-03-19 21:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0148_alter_attribute_help_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeLock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='timestamp')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_lock', to='projects.attribute', verbose_name='attribute')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_lock', to='projects.project', verbose_name='project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_lock', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'unique_together': {('project', 'attribute')},
            },
        ),
    ]
