# Generated by Django 3.2.16 on 2023-03-31 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0149_attributelock'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributelock',
            name='fieldset_attribute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attribute_lock_fieldset', to='projects.attribute', verbose_name='fieldset_attribute'),
        ),
        migrations.AddField(
            model_name='attributelock',
            name='fieldset_attribute_index',
            field=models.IntegerField(null=True, verbose_name='index'),
        ),
        migrations.AlterField(
            model_name='attributelock',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='timestamp'),
        ),
    ]
