# Generated by Django 3.2.16 on 2023-04-06 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0150_auto_20230331_1059'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attributelock',
            options={'verbose_name': 'attribute lock', 'verbose_name_plural': 'attribute locks'},
        ),
        migrations.AlterField(
            model_name='attributelock',
            name='fieldset_attribute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attribute_lock_fieldset', to='projects.attribute', verbose_name='fieldset attribute'),
        ),
        migrations.AlterUniqueTogether(
            name='attributelock',
            unique_together={('project', 'attribute', 'fieldset_attribute', 'fieldset_attribute_index')},
        ),
    ]
