# Generated by Django 3.2.16 on 2023-04-21 10:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from projects.models.project import ProjectPriority


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0152_auto_20230406_1118'),
    ]

    def create_default_priority(self, schema_editor):
        if not ProjectPriority.objects.count():
            try:
                ProjectPriority.objects.create(priority=5, name='Kärkihanke')
            except Exception:
                pass

    operations = [
        migrations.CreateModel(
            name='ProjectPriority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.PositiveIntegerField(default=1, unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='priority')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='priority name')),
            ],
            options={
                'verbose_name': 'project priority',
                'verbose_name_plural': 'project priorities',
                'ordering': ('priority',),
            },
        ),
        migrations.AddField(
            model_name='project',
            name='priority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='projects.projectpriority', verbose_name='project priority'),
        ),
        migrations.RunPython(create_default_priority, migrations.RunPython.noop),
    ]
