# Generated by Django 3.2.19 on 2023-05-11 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0153_auto_20230421_1334'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectpriority',
            options={'ordering': ('-priority',), 'verbose_name': 'project priority', 'verbose_name_plural': 'project priorities'},
        ),
    ]
