# Generated by Django 3.2.19 on 2023-06-09 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0154_alter_projectpriority_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='field_roles',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Field roles'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='field_subroles',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Field subroles'),
        ),
    ]
