# Generated by Django 3.2.19 on 2023-06-27 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0155_auto_20230609_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='field_roles',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Field roles'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='field_subroles',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Field subroles'),
        ),
    ]
