# Generated by Django 3.2.19 on 2023-08-24 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0156_auto_20230627_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdocumentdownloadlog',
            name='invalidated',
            field=models.BooleanField(default=False),
        ),
    ]
