# Generated by Django 3.2.19 on 2023-10-06 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0158_alter_attributelock_attribute'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectphasesection',
            name='ingress',
            field=models.CharField(default='', max_length=255, verbose_name='ingress'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='value_type',
            field=models.CharField(choices=[('fieldset', 'fieldset'), ('info_fieldset', 'info fieldset'), ('integer', 'integer'), ('decimal', 'decimal'), ('short_string', 'short string'), ('long_string', 'long string'), ('rich_text', 'rich text'), ('rich_text_short', 'short rich text'), ('boolean', 'boolean'), ('date', 'date'), ('user', 'user'), ('personnel', 'personnel'), ('geometry', 'geometry'), ('image', 'image'), ('file', 'file'), ('link', 'link'), ('choice', 'choice')], max_length=64, verbose_name='value type'),
        ),
    ]
