# Generated by Django 3.2.19 on 2023-10-06 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0158_alter_attributelock_attribute'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='ingress',
            field=models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='ingress'),
        ),
    ]
