# Generated by Django 3.2.19 on 2023-10-06 13:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0159_auto_20231006_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='linked_fields',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), blank=True, null=True, size=None),
        ),
    ]
