# Generated by Django 3.2.19 on 2023-10-18 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0160_attribute_linked_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdeadline',
            name='edited',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='modified at'),
        ),
    ]
