# Generated by Django 3.2.19 on 2023-10-19 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0161_projectdeadline_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='assistive_text',
            field=models.TextField(blank=True, null=True, verbose_name='assistive text'),
        ),
    ]
