# Generated by Django 3.2.19 on 2023-11-03 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0163_attribute_validation_regex'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeCategorization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('includes_principles', models.BooleanField(verbose_name='includes principles')),
                ('includes_draft', models.BooleanField(verbose_name='includes draft')),
                ('value', models.CharField(max_length=128, verbose_name='value')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorizations', to='projects.attribute', verbose_name='attribute')),
                ('common_project_phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorizations', to='projects.commonprojectphase', verbose_name='phase')),
            ],
            options={
                'verbose_name': 'attribute categorization',
                'verbose_name_plural': 'attribute categorizations',
                'unique_together': {('attribute', 'common_project_phase', 'includes_principles', 'includes_draft')},
            },
        ),
    ]
