# Generated by Django 3.2.25 on 2024-12-18 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0168_alter_attribute_help_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='help_link',
            field=models.URLField(blank=True, max_length=2048, null=True, verbose_name='Help link'),
        ),
    ]
