# Generated by Django 3.2.19 on 2024-05-15 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0168_alter_attribute_help_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='deadline',
            name='group',
            field=models.TextField(blank=True, null=True, verbose_name='group'),
        ),
        migrations.AddField(
            model_name='deadline',
            name='subgroup',
            field=models.TextField(blank=True, null=True, verbose_name='subgroup'),
        ),
    ]
