# Generated by Django 3.2.19 on 2024-05-15 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0169_auto_20240515_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deadline',
            name='group',
        ),
        migrations.RemoveField(
            model_name='deadline',
            name='subgroup',
        ),
        migrations.AddField(
            model_name='deadline',
            name='deadlinegroup',
            field=models.TextField(blank=True, null=True, verbose_name='deadlinegroup'),
        ),
        migrations.AddField(
            model_name='deadline',
            name='deadlinesubgroup',
            field=models.TextField(blank=True, null=True, verbose_name='deadlinesubgroup'),
        ),
    ]
