# Generated by Django 3.2.19 on 2024-05-21 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0172_auto_20240515_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deadline',
            name='deadlinesubgroup',
        ),
    ]
