# Generated by Django 3.2.19 on 2024-05-15 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0172_auto_20240515_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='deadline',
            name='deadlinegroup',
            field=models.TextField(blank=True, null=True, verbose_name='deadlinegroup'),
        ),
        migrations.AddField(
            model_name='deadline',
            name='deadlinesubgroup',
            field=models.TextField(blank=True, null=True, verbose_name='deadlinesubgroup'),
        ),
    ]
