# Generated by Django 3.2.25 on 2024-10-04 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0174_remove_deadline_deadlinesubgroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deadlinedistance',
            name='conditions',
        ),
        migrations.AddField(
            model_name='deadlinedistance',
            name='condition_operator',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.CreateModel(
            name='DeadlineDistanceConditionAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('negate', models.BooleanField(default=False)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.attribute')),
            ],
        ),
        migrations.AddField(
            model_name='deadlinedistance',
            name='condition_attributes',
            field=models.ManyToManyField(blank=True, related_name='deadline_distances', to='projects.DeadlineDistanceConditionAttribute'),
        ),
    ]
