# Generated by Django 3.2.25 on 2024-11-05 08:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0175_auto_20241004_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='datetype',
            name='forced_dates',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateField(), blank=True, null=True, size=None, verbose_name='forced dates'),
        ),
    ]
