# Generated by Django 3.2.25 on 2025-01-30 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0177_alter_attribute_help_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForcedDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_date', models.DateField(blank=True, null=True, verbose_name='date_original')),
                ('new_date', models.DateField(verbose_name='date_new')),
            ],
        ),
        migrations.RemoveField(
            model_name='datetype',
            name='forced_dates',
        ),
        migrations.AddField(
            model_name='datetype',
            name='forced_dates',
            field=models.ManyToManyField(blank=True, to='projects.ForcedDate', verbose_name='dates_forced'),
        ),
    ]
