# Generated by Django 3.2.25 on 2025-02-10 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0178_auto_20250130_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='viewing_privilege',
            field=models.CharField(blank=True, choices=[(None, 'Ei roolia'), ('browse', 'Selaaja'), ('edit', 'Asiantuntija'), ('create', 'Vastuuhenkilö'), ('admin', 'Pääkäyttäjä')], default=None, max_length=6, null=True, verbose_name='privilege for viewing timetable items'),
        ),
    ]
