# Generated by Django 3.2.25 on 2025-02-21 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0179_attribute_viewing_privilege'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forceddate',
            name='new_date',
            field=models.DateField(blank=True, null=True, unique=True, verbose_name='date_new'),
        ),
        migrations.AlterField(
            model_name='forceddate',
            name='original_date',
            field=models.DateField(blank=True, null=True, unique=True, verbose_name='date_original'),
        ),
    ]
