# Generated by Django 3.2.25 on 2025-02-28 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0180_auto_20250221_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='api_visibility',
            field=models.BooleanField(default=False, verbose_name='Visible to Kaavoitus-API'),
        ),
    ]
