# Generated by Django 3.2.25 on 2025-04-04 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0181_attribute_api_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='help_img_link',
            field=models.URLField(blank=True, max_length=2048, null=True, verbose_name='Help image link'),
        ),
    ]
