# Generated by Django 3.2.25 on 2025-06-05 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0182_attribute_help_img_link'),
        ('projects', '0182_projectdeadline_editable'),
    ]

    operations = [
    ]
