<<<<<<< HEAD
# Generated by Django 4.2.24 on 2026-01-07 10:13

from django.db import migrations, models
=======
# Generated by Django 3.2.25 on 2026-01-08 00:00

from django.db import migrations, models
from django.utils import timezone


def set_onhold_timestamps(apps, schema_editor):
    Project = apps.get_model("projects", "Project")
    for project in Project.objects.filter(onhold=True, onhold_at__isnull=True):
        project.onhold_at = timezone.now()
        project.save(update_fields=["onhold_at"])


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0183_merge_20250605_1354"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="onhold_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="on hold at"),
        ),
        migrations.RunPython(set_onhold_timestamps, migrations.RunPython.noop),
    ]
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="onhold_at",
<<<<<<< HEAD
            field=models.DateTimeField(blank=True, null=True, verbose_name="onhold at"),
        ),
=======
            field=models.DateTimeField(blank=True, null=True, verbose_name="on hold at"),
        ),
        migrations.RunPython(set_onhold_timestamps, migrations.RunPython.noop),
>>>>>>> b779e7a (Restore on-hold timestamp and repair migration pytest kept crashing because the serializer/admin still toggle Project.onhold_at but the column no longer existed. Migration 0184 adds the field back while the model/admin/serializer changes keep behaviour consistent. That exposed migration 0166 importing the live Project model, which now included onhold_at and caused undefined-column errors on fresh DBs. Switching the data migration to use apps.get_model ties it to the historical schema so migrations (and tests) run cleanly.)
    ]
