# Generated by Django 3.2.25 on 2026-01-08 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0183_merge_20250605_1354"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="onhold_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="onhold at"),
        ),
    ]
