# Generated by Django 4.2.27 on 2026-02-11 10:44

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0184_project_onhold_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributevaluechoice',
            name='identifier',
            field=models.CharField(db_index=True, max_length=512, validators=[django.core.validators.RegexValidator(re.compile('^[\\w]+\\Z'), "Enter a valid 'identifier' consisting of Unicode letters, numbers or underscores.", 'invalid')], verbose_name='identifier'),
        ),
    ]
