# Generated by Django 4.2.16 on 2026-04-14 09:41

from django.db import migrations, models

def update_legacy_identifier(apps, schema_editor):
    AttributeValueChoice = apps.get_model("projects", "AttributeValueChoice")
    for value_choice in AttributeValueChoice.objects.all():
        value_choice.legacy_identifier = value_choice.identifier
        value_choice.save()

class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0185_alter_attributevaluechoice_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributevaluechoice',
            name='legacy_identifier',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='attributevaluechoice',
            name='index',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='index'),
        ),
        migrations.RunPython(update_legacy_identifier, migrations.RunPython.noop),
    ]
