# Generated by Django 4.2.16 on 2026-09-07 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0186_attributevaluechoice_legacy_identifier_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalReportLink",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        help_text="Link to the external website where report documents are stored.",
                        verbose_name="external report portal url",
                    ),
                ),
            ],
            options={
                "verbose_name": "external report link",
                "verbose_name_plural": "external report link",
            },
        ),
    ]
