# Generated by Django 4.2.16 on 2026-09-08 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0187_external_report_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="externalreportlink",
            name="url",
            field=models.URLField(
                help_text="Link to the external website where report documents are stored.",
                max_length=1024,
                verbose_name="external report portal url",
            ),
        ),
    ]
