stages:
- name: Build
  steps:
  - runScriptConfig:
      image: python:3.6.6-slim-stretch
      shellScript: |-
        echo do what?
- name: Publish image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: api:${CICD_EXECUTION_SEQUENCE}-${CICD_GIT_COMMIT}
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deploy/rancher/deployment.yaml
  when:
    branch:
      include:
      - development
notification: {}
