# This is a sample build configuration for Python.
# Check our guides at https://confluence.atlassian.com/x/x4UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: python:3.9

options:
  size: 2x

definitions:
  services:
    docker:
      memory: 4048

pipelines:
  default:
    - step:
        caches:
          - pip
        script: # Modify the commands below to build your repository.
          - pip install -r requirements.txt
  branches:
    '{development,test}':
      - step:
          name: Build docker image
          caches:
            - docker
          script:
          - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
          - docker build -f Dockerfile_unikie_dev_cluster -t kleklekle/spia:kaavapino-api-$BITBUCKET_BUILD_NUMBER-$BITBUCKET_COMMIT --build-arg REDHAT_USERNAME=$REDHAT_USERNAME --build-arg REDHAT_PASSWORD=$REDHAT_PASSWORD .
          - docker push kleklekle/spia:kaavapino-api-$BITBUCKET_BUILD_NUMBER-$BITBUCKET_COMMIT
          services:
          - docker
      - step:
          name: Deploy
          caches:
            - docker
          deployment: production
          script:
            - sed -i 's|${CICD_EXECUTION_SEQUENCE}|'$BITBUCKET_BUILD_NUMBER'|g' deploy/rancher/deployment.yaml
            - sed -i 's|${CICD_GIT_COMMIT}|'$BITBUCKET_COMMIT'|g' deploy/rancher/deployment.yaml
            - pipe: atlassian/kubectl-run:3.1.2
              variables:
                KUBE_CONFIG: $KUBE_CONFIG
                KUBECTL_COMMAND: 'apply'
                RESOURCE_PATH: 'deploy/rancher/deployment.yaml'
                KUBECTL_ARGS:
                  - '--namespace=p-c94d9-pipeline'
