version: "3.5"
services:
  db:
    image: skywidesoft/postgis-hstore
    environment:
       - POSTGRES_USER=kaavapino
       - POSTGRES_PASSWORD=kaavapino
       - POSTGRES_DB=kaavapino
    volumes:
      - db_kaavapino_data:/var/lib/postgresql
    ports:
      - "5432:5432"
    container_name: kaavapino-db

  cache:
    image: eqalpha/keydb
    container_name: kaavapino-keydb
    command: keydb-server /etc/keydb/keydb.conf --server-threads 2
    volumes:
      - ./keydb.conf:/etc/keydb/keydb.conf
      - cache_kaavapino_data:/data
    ports:
      - "6379:6379"
    restart: on-failure

  api:
    build:
      target: "test"
      context: "."
      #dockerfile: Dockerfile_local_with_subscription
      #args:
      #  REDHAT_USERNAME:
      #  REDHAT_PASSWORD:
    entrypoint: /docker-entrypoint.sh
    image: kaavapino
    volumes:
      - .:/kaavapino
    environment:
      - DEBUG=1
      - DATABASE_URL=postgis://kaavapino:kaavapino@db/kaavapino
      - KEYDB_URL=redis://cache
      - TOKEN_AUTH_ACCEPTED_AUDIENCE=https://api.hel.fi/auth/kaavapinodev
      - TOKEN_AUTH_ACCEPTED_SCOPE_PREFIX=kaavapinodev
      - REQUIRE_API_SCOPE_FOR_AUTHENTICATION=False
      - TOKEN_AUTH_AUTHSERVER_URL=https://api.hel.fi/sso/openid
      - ALLOWED_HOSTS=localhost
      - DOCUMENT_EDIT_URL_FORMAT=
      - CSRF_TRUSTED_ORIGINS=
      - SOCIAL_AUTH_TUNNISTAMO_KEY=
      - SOCIAL_AUTH_TUNNISTAMO_OIDC_ENDPOINT=
      - SOCIAL_AUTH_TUNNISTAMO_SECRET=
      - KAAVOITUS_API_BASE_URL=
      - KAAVOITUS_API_AUTH_TOKEN=
      - GRAPH_API_LOGIN_BASE_URL=https://login.microsoftonline.com
      - GRAPH_API_BASE_URL=https://graph.microsoft.com
      - GRAPH_API_APPLICATION_ID=
      - GRAPH_API_TENANT_ID=
      - GRAPH_API_CLIENT_SECRET=
    ports:
      - "8000:8000"
    depends_on:
      - db
      - cache
    container_name: kaavapino-api

  django-q:
    build:
      context: "."
      #dockerfile: Dockerfile_local_with_subscription
      #args:
      #  REDHAT_USERNAME:
      #  REDHAT_PASSWORD:
    command: python /kaavapino/manage.py qcluster
    volumes:
      - .:/kaavapino
    depends_on:
      - db
      - cache
      - api
    restart: on-failure
    environment:
      - DATABASE_URL=postgis://kaavapino:kaavapino@db/kaavapino
      - KEYDB_URL=redis://cache
      - KAAVOITUS_API_BASE_URL=
      - KAAVOITUS_API_AUTH_TOKEN=
      - GRAPH_API_LOGIN_BASE_URL=https://login.microsoftonline.com
      - GRAPH_API_BASE_URL=https://graph.microsoft.com
      - GRAPH_API_APPLICATION_ID=
      - GRAPH_API_TENANT_ID=
      - GRAPH_API_CLIENT_SECRET=
      - ALLOWED_HOSTS=localhost
      - CSRF_TRUSTED_ORIGINS=
      - DOCUMENT_EDIT_URL_FORMAT=
    container_name: kaavapino-django-q

volumes:
    db_kaavapino_data:
    cache_kaavapino_data:
