##### Base image #####
FROM registry.access.redhat.com/ubi8/python-39:1-22.1638364042 as base

ENV PYTHONUNBUFFERED 1
ENV DEBIAN_FRONTEND noninteractive
ENV APP_NAME kaavapino
# Set defaults for Django paths as appropriate for this container
#ENV STATIC_ROOT /srv/static
#ENV MEDIA_ROOT /srv/media

USER root

# Name the workdir after the project, makes it easier to
# know where you are when troubleshooting
RUN mkdir /$APP_NAME
WORKDIR /$APP_NAME

ARG REDHAT_USERNAME
ARG REDHAT_PASSWORD

RUN subscription-manager register --username $REDHAT_USERNAME --password $REDHAT_PASSWORD --auto-attach --force
RUN subscription-manager repos --enable codeready-builder-for-rhel-8-x86_64-rpms
RUN dnf -y update
RUN dnf -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
RUN dnf install -y \
    git \
    binutils \
    gdal \
    geos \
    nc \
    vim

# Upgrade pip
RUN pip install -U pip

# Install Poetry
RUN pip install poetry

RUN groupadd -g 1003 kaavapinogroup && useradd -u 1002 -g kaavapinogroup kaavapinouser
#RUN mkdir -p $STATIC_ROOT $MEDIA_ROOT

RUN subscription-manager remove --all || :
RUN subscription-manager unregister || :
RUN subscription-manager clean || :


##### Test image #####
FROM base AS test

# Install python dependencies
COPY poetry.lock pyproject.toml /$APP_NAME/
RUN poetry export -f requirements.txt --output requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Add entrypoint script
ADD docker-entrypoint.sh /
RUN chmod +x /docker-entrypoint.sh


##### Server image #####
FROM base AS deploy

# Install python dependencies
COPY poetry.lock pyproject.toml ./
ADD deploy/requirements.txt ./deploy/requirements.txt
RUN poetry export --without dev -f requirements.txt --output requirements.txt
RUN pip install --no-cache-dir -r ./deploy/requirements.txt

COPY . .

#RUN chown -Rh kaavapinouser:kaavapinogroup /$APP_NAME
#RUN chown -Rh kaavapinouser:kaavapinogroup /$STATIC_ROOT
#RUN chown -Rh kaavapinouser:kaavapinogroup /$MEDIA_ROOT

USER kaavapinouser

CMD deploy/server.sh
