# Generated by Django 2.2.13 on 2020-07-03 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FooterSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('index', models.PositiveIntegerField(default=0, verbose_name='index')),
            ],
            options={
                'verbose_name': 'footer section',
                'verbose_name_plural': 'footer sections',
                'ordering': ('index',),
            },
        ),
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_text', models.CharField(max_length=255, verbose_name='link text')),
                ('url', models.CharField(max_length=255, verbose_name='url')),
                ('index', models.PositiveIntegerField(default=0, verbose_name='index')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='sitecontent.FooterSection', verbose_name='section')),
            ],
            options={
                'verbose_name': 'footer link',
                'verbose_name_plural': 'footer link',
                'ordering': ('index',),
            },
        ),
    ]
