# Generated by Django 2.2.13 on 2020-10-15 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0071_attribute_static_property'),
        ('sitecontent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListViewAttributeColumn',
            fields=[
                ('index', models.PositiveIntegerField(default=0)),
                ('attribute', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='projects.Attribute')),
            ],
            options={
                'ordering': ('index',),
            },
        ),
    ]
