# Generated by Django 3.2.10 on 2022-04-21 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitecontent', '0003_auto_20210520_1058'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='targetfloorarea',
            options={'verbose_name': 'Asuinkerrosalan vuositavoite', 'verbose_name_plural': 'Asuinkerrosalan vuositavoitteet'},
        ),
    ]
