# Generated by Django 3.2.25 on 2024-09-11 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecontent', '0004_alter_targetfloorarea_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(unique=True, upload_to='excel_files/')),
                ('uploaded', models.DateTimeField(auto_now_add=True, verbose_name='upload date')),
                ('type', models.CharField(choices=[('attributes', 'attributes'), ('deadlines', 'deadlines'), ('unknown', 'unknown')], default='unknown', max_length=32)),
                ('status', models.CharField(choices=[('inactive', 'inactive'), ('updating', 'updating'), ('active', 'active'), ('error', 'error')], default='inactive', max_length=32)),
                ('updated', models.DateTimeField(null=True, verbose_name='update date')),
                ('options', models.CharField(default='{"kv":"1.0"}', max_length=32, null=True)),
                ('task_id', models.CharField(max_length=64, null=True)),
                ('error', models.CharField(max_length=2048, null=True)),
            ],
        ),
    ]
