# Generated by Django 3.2.25 on 2024-11-26 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecontent', '0005_excelfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footerlink',
            name='url',
            field=models.CharField(max_length=511, verbose_name='url'),
        ),
    ]
