# Generated by Django 4.2.16 on 2026-04-30 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecontent', '0006_alter_footerlink_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excelfile',
            name='options',
            field=models.CharField(default='{}', max_length=32, null=True),
        ),
    ]
